version: "2"

services:

  phpmyfaq:
    build: .
    links:
    - mariadb
    - elasticsearch
    ports:
    - "8080:80"
    volumes:
    - attachments:/var/www/html/phpmyfaq/attachments
    - config:/var/www/html/phpmyfaq/config
    - data:/var/www/html/phpmyfaq/data
    - images:/var/www/html/phpmyfaq/images

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - mariadb:db
    ports:
    - "8001:80"
    volumes:
    - phpmyadmin-sessions:/sessions

  mariadb:
    image: mariadb:10.1.21
    environment:
    - MYSQL_ROOT_PASSWORD=iop
    - MYSQL_DATABASE=phpmyfaq
    - MYSQL_USER=phpmyfaq
    - MYSQL_PASSWORD=phpmyfaq
    volumes:
    - mariadb-data:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:5.2.0
    volumes:
    - es-data:/usr/share/elasticsearch/data

volumes:
  attachements:
    driver: local
  config:
    driver: local
    external:
      name: phpmyfaq-config
  data:
    driver: local
  images:
    driver: local
  phpmyadmin:
    driver: local
  es-data:
    driver: local


