version: "2"

services:

  phpmyfaq:
    build: ./phpmyfaq
    links:
    - mariadb
    - elasticsearch
    ports:
    - "80:80"

  mariadb:
    image: mariadb:10.1.21
    environment:
    - MYSQL_ROOT_PASSWORD=iop
    - MYSQL_DATABASE=phpmyfaq
    - MYSQL_USER=phpmyfaq
    - MYSQL_PASSWORD=phpmyfaq

  elasticsearch:
    image: elasticsearch:5.2.0
    command:
    - -Des.node.name="phpMyFAQ"
