version: "2"

services:

  phpmyfaq:
    build: ./phpmyfaq
    links:
    - mariadb:db
    ports:
    - "80:80"

  mariadb:
    image: mariadb:10.1.21
    environment:
    - MYSQL_ROOT_PASSWORD=iop
    - MYSQL_DATABASE=phpmyfaq
    - MYSQL_USER=phpmyfaq
    - MYSQL_PASSWORD=phpmyfaq

