version: "2"

services:

  phpmyfaq:
    build: ./phpmyfaq
    links:
    - mariadb
    - elasticsearch
    ports:
    - "8080:80"
    volumes:
    - ./volumes/phpmyfaq-attachments:/var/www/html/phpmyfaq/attachments
    - ./volumes/phpmyfaq-data:/var/www/html/phpmyfaq/data
    - ./volumes/phpmyfaq-images:/var/www/html/phpmyfaq/images

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - mariadb:db
    ports:
    - "8001:80"
    volumes:
    - ./volumes/phpmyadmin-sessions:/sessions
    environment:
    - MYSQL_ROOT_PASSWORD=iop

  mariadb:
    image: mariadb:10.1.21
    environment:
    - MYSQL_ROOT_PASSWORD=iop
    - MYSQL_DATABASE=phpmyfaq
    - MYSQL_USER=phpmyfaq
    - MYSQL_PASSWORD=phpmyfaq
    volumes:
    - ./volumes/mariadb-data:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:5.2.0
    command: -Des.node.name="phpMyFAQ"
    volumes:
    - ./volumes/elasticsearch-data:/usr/share/elasticsearch/data

